### ISSUE TITLE
Accessibility icon is hidden behind the alert dialog

### ISSUE THREAD

**Issue by Praveenmishra123** [dequelabs/axe-devtools-android-sample-app#9]
I have an activity where I am displaying an alert dialog to the user. When an alert dialog is displaying I can not see the accessibility icon and as soon as I dismiss the alert dialog accessibility icon is displayed on the screen. 

Is it possible to display the accessibility icon on top of the alert dialog?

**Comment by karnett** [comment]
Hi There -- 
Thanks for checking out our sample app.

We do have an issue for this use case in our backlog. If you'd like an update once it's released, you can submit a ticket at support.deque.com and will get a direct response as we have updates. Additionally, if you have any other bugs to report with the framework itself, please do so at support.deque.com.

More info and links available in our public docs as well:
https://docs.deque.com/devtools-mobile/2022.6.6/en/help

Thanks!

**Comment by jaaveethhaja-mset** [comment]
Is this issue resolved?
